### ISSUE TITLE
error: use of undeclared identifier 'processGepPts'

### ISSUE THREAD

**Issue by wanghaichi** [seclab-ucr/Unias#2]
When building the project, I encountered the following error:

`Unias/src/Steensgaard.cpp:115:21: error: use of undeclared identifier 'processGepPts'
                    processGepPts(gepEdge);`
It seems due to the wrong usage of SVF apis.
The definition of processGepPts is as follows:

`./include/WPA/Andersen.h:    virtual bool processGepPts(const PointsTo& pts, const GepCGEdge* edge);`

which takes two arguments.

SVF version: tag SVF-2.5
LLVM: 14

CC: clang-14

**Comment by guoren97** [comment]
to resolve this, please patch Steensgaard's processGepPts() function in the source code of SVF-2.5 and rebuild it:

in include/WPA/Steensgaard.h
add following at around line 55:
```
void processGepPts(const NormalGepCGEdge* edge);
```

in lib/WPA/Steensgaard.cpp
add following at around line 19:
```
void Steensgaard::processGepPts(const NormalGepCGEdge *edge){
    PointsTo tmpDstPts;
    for (NodeID o : getPts(edge->getSrcID())){
        auto fieldSrcPtdNode = consCG->getGepObjVar(o, edge->getLocationSet());
        tmpDstPts.set(fieldSrcPtdNode);
    }
    NodeID dstId = edge->getDstID();
    if(unionPts(dstId, tmpDstPts)){
        pushIntoWorklist(dstId);
    }
}
```

**Comment by wanghaichi** [comment]
Thanks! This error is solved. 
However, another error occurred. 

```
BreakConstantExpr.cpp:(.text+0x2c2): undefined reference to `llvm::ConstantExpr::getAsInstruction() const'
/usr/bin/ld: BreakConstantExpr.cpp:(.text+0x48e): undefined reference to `llvm::ConstantExpr::getAsInstruction() const'
/usr/bin/ld: /home/wanghaichi/SVF/Release-build/lib/libSvf.a(CHG.cpp.o): in function `llvm::GraphWriter<SVF::CHGraph*>::writeNode(SVF::CHNode*)':

PTACallGraph.cpp:(.text+0xb3f): undefined reference to `llvm::raw_string_ostream::~raw_string_ostream()'
/usr/bin/ld: /home/wanghaichi/SVF/Release-build/lib/libSvf.a(PTACallGraph.cpp.o): in function `SVF::PTACallGraphEdge::toString[abi:cxx11]() const':
```

Compile command:

CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14   cmake -DCMAKE_BUILD_TYPE=Release -DSVF_DIR=/home/wanghaichi/SVF -DLLVM_DIR=/usr/lib/llvm-14/build/lib/cmake ..

CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14 LD=ld.lld make -j`nproc`

This seems due to LLVM library is not found by SVF. One concern is SVF-2.5 uses LLVM-13, while here LLVM-14 is used.
Any idea to solve this?

Environments:
LLVM-14 to $PATH

**Comment by wanghaichi** [comment]
I found SVF-2.7 supports LLVM-14, however, when upgrading SVF to 2.7, there is no include/WPA/Steensgaard.h file.

**Comment by guoren97** [comment]
please also use llvm-14 for SVF-2.5

you can try to manually specify env variable LLVM_DIR in the root CMakeLists.txt of SVF-2.5, like following

```
project("SVF")
set(ENV{LLVM_DIR} /path/to/llvm-14.0.6.build/lib/cmake)
```

rebuild the SVF-2.5 and it will use the specified llvm-14-lib instead of downloading llvm-13-lib from the internet

**Comment by wanghaichi** [comment]
Thanks! It works!
